# ========================
# DEPLOYMENT: render.yaml
# Description: Render.com deployment configuration
# ========================

services:
  # Frontend web service
  - type: web
    name: msword-lite-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: msword-lite-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend API service
  - type: web
    name: msword-lite-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
